# Generated by Django 5.1.6 on 2025-07-08 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_name',
            new_name='name',
        ),
    ]
